#!/usr/bin/env node
/**
 * widgets/install.mjs — put the skins where Rainmeter can see them.
 *
 * Copies widgets/skins/Claudbot into the Rainmeter skins folder and generates
 * @Resources/paths.inc holding this machine's absolute paths.
 *
 * Generating that file is the whole point. Rainmeter has no notion of a
 * relative path or an environment variable, so a skin has to name the Node
 * binary and the data directory outright — and Claudbot's rules forbid checking
 * such a path into the repo. So the committed skins reference #NodeExe# and
 * #DataDir#, and this script writes the one file that defines them, resolved
 * through portable/paths.mjs and process.execPath at install time.
 *
 *   node widgets/install.mjs              install / update
 *   node widgets/install.mjs --uninstall  remove the installed copy
 */

import {
  existsSync, mkdirSync, cpSync, rmSync, readFileSync, writeFileSync, readdirSync,
} from "node:fs";
import path from "node:path";
import os from "node:os";
import { appDir } from "../portable/paths.mjs";

const ROOT     = appDir();
const SRC      = path.join(ROOT, "widgets", "skins", "Claudbot");
const DATA_DIR = path.join(ROOT, ".claudbot", "widgets");
const BRIDGE   = path.join(ROOT, "widgets", "bridge.mjs");
const CLAUDBOT = path.join(ROOT, "claudbot.mjs");

/**
 * Rainmeter's skins folder.
 *
 * Ask Rainmeter, don't guess. It records the folder as SkinPath in
 * Rainmeter.ini, and that value is authoritative — the user can relocate it,
 * and OneDrive's Documents redirection moves it out from under the obvious
 * ~/Documents guess. Installing to the wrong folder fails silently: Rainmeter
 * simply doesn't list the skin, with no error anywhere.
 *
 * The guessed paths are only a fallback for installing before Rainmeter has
 * ever been run, since it doesn't write Rainmeter.ini until first launch.
 */
function skinsRoot() {
  if (process.env.RAINMETER_SKINS) return { dir: process.env.RAINMETER_SKINS, source: "RAINMETER_SKINS" };

  const home = os.homedir();

  // Rainmeter.ini lives in AppData, or beside the exe in portable mode.
  const iniPaths = [
    path.join(process.env.APPDATA ?? path.join(home, "AppData", "Roaming"), "Rainmeter", "Rainmeter.ini"),
    "C:\\Program Files\\Rainmeter\\Rainmeter.ini",
  ];
  for (const ini of iniPaths) {
    if (!existsSync(ini)) continue;
    try {
      // Rainmeter writes this file as UTF-16LE.
      const text = readFileSync(ini, "utf16le");
      const m = text.match(/^\s*SkinPath\s*=\s*(.+?)\s*$/mi);
      if (m?.[1]) return { dir: m[1].replace(/[\\/]+$/, ""), source: ini };
    } catch { /* fall through to the guesses */ }
  }

  const bases = [
    process.env.OneDrive ? path.join(process.env.OneDrive, "Documents") : null,
    path.join(home, "OneDrive", "Documents"),
    path.join(home, "Documents"),
  ].filter(Boolean);
  const candidates = bases.map((b) => path.join(b, "Rainmeter", "Skins"));

  const found = candidates.find(existsSync);
  if (found) return { dir: found, source: "guessed (Rainmeter not yet run)" };
  return { dir: candidates.at(-1), source: "assumed (Rainmeter not installed)" };
}

/**
 * Re-encode every copied .ini/.inc as UTF-16LE with a BOM.
 *
 * Rainmeter reads skin files as ANSI unless they are UTF-16 — a UTF-8 BOM is
 * not enough, verified by trying it: a "○" bullet still arrived on screen as
 * "â—‹" after a full restart. Data files read through WebParser are a separate
 * path and are fine as UTF-8 (CodePage=65001).
 *
 * The repo keeps these files as UTF-8 so they stay diffable and editable; the
 * conversion happens here, on the installed copy only.
 */
function toUtf16(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) { toUtf16(p); continue; }
    if (!/\.(ini|inc)$/i.test(entry.name)) continue;
    const buf = readFileSync(p);
    if (buf[0] === 0xff && buf[1] === 0xfe) continue; // already UTF-16LE
    const text = buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf
      ? buf.subarray(3).toString("utf8")
      : buf.toString("utf8");
    writeFileSync(p, Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(text, "utf16le")]));
  }
}

function generatePathsInc(dest) {
  const inc = `; ─────────────────────────────────────────────────────────────────────────────
; GENERATED by widgets/install.mjs — do not edit, and do not commit.
;
; Rainmeter can't read an environment variable or resolve a relative path, so
; the machine-specific locations have to be written out literally. Re-run
; \`node widgets/install.mjs\` after moving the Claudbot checkout.
;
; Generated ${new Date().toISOString()}
; ─────────────────────────────────────────────────────────────────────────────

[Variables]
NodeExe=${process.execPath}
DataDir=${DATA_DIR}
Bridge=${BRIDGE}
Claudbot=${CLAUDBOT}
AppDir=${ROOT}
`;
  writeFileSync(path.join(dest, "@Resources", "paths.inc"), inc);
}

function main() {
  const uninstall = process.argv.includes("--uninstall");
  const { dir: root, source } = skinsRoot();
  const dest = path.join(root, "Claudbot");

  if (uninstall) {
    if (existsSync(dest)) {
      rmSync(dest, { recursive: true, force: true });
      console.log(`[widgets] removed ${dest}`);
    } else {
      console.log(`[widgets] nothing installed at ${dest}`);
    }
    return;
  }

  if (!existsSync(SRC)) {
    console.error(`[widgets] source skins missing: ${SRC}`);
    process.exit(1);
  }

  const rainmeterPresent = !source.startsWith("assumed");

  mkdirSync(path.join(dest, "@Resources"), { recursive: true });

  // Copy the skins but never the generated paths.inc from a previous install —
  // it's regenerated below, and copying a stale one from source would be a
  // silent way to point a fresh machine at another machine's directories.
  cpSync(SRC, dest, {
    recursive: true,
    filter: (src) => path.basename(src) !== "paths.inc",
  });

  // Generate before converting so paths.inc gets the same UTF-16 treatment.
  generatePathsInc(dest);
  toUtf16(dest);

  mkdirSync(DATA_DIR, { recursive: true });

  const skins = readdirSync(dest, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith("@"))
    .map((e) => e.name);

  console.log(`[widgets] installed to ${dest}`);
  console.log(`[widgets] via:   ${source}`);
  console.log(`[widgets] skins: ${skins.join(", ")}`);
  console.log(`[widgets] node:  ${process.execPath}`);
  console.log(`[widgets] data:  ${DATA_DIR}`);

  if (!rainmeterPresent) {
    console.log("");
    console.log("[widgets] NOTE: Rainmeter doesn't look installed yet.");
    console.log("[widgets]       winget install --id Rainmeter.Rainmeter -e");
    console.log("[widgets]       Then re-run this script so it finds the right skins folder.");
  } else {
    console.log("");
    console.log("[widgets] Next: right-click the Rainmeter tray icon > Refresh all,");
    console.log("[widgets]       then load Claudbot > Status / PostIt / Stocks / Todo.");
    console.log("[widgets]       Start the data feed with:  claudbot widgets");
  }
}

main();
