"""
Train the bilingual "Hey Aitor" wake word for openWakeWord.

openWakeWord ships no model for this phrase, so one has to be trained from
synthetic speech. The important twist here is **bilingual**: "Aitor" is a Basque
name, and an English speaker's "eye-tor" and a Spanish speaker's "ay-tor" are
acoustically different enough that a model trained on one misses the other. So
the phrase list below deliberately spans both pronunciations and the generator
is pointed at both English and Spanish Piper voices — one model, both accents.

Two paths:

  python -m voice.train_wakeword            write the config, then train if the
                                            training extras are installed
  python -m voice.train_wakeword --config   only write the config + Colab recipe

Training needs a GPU to be tolerable (~30-60 min). Without one, use the Colab
notebook the script prints — the config it writes is the notebook's input.

After training, drop the resulting `hey_aitor.onnx` in voice/models/ (or set
CLAUDBOT_VOICE_WAKE_MODEL) and restart `claudbot voice`.
"""
from __future__ import annotations

import sys
from pathlib import Path

from . import config as cfg

# Both pronunciations, plus the near-misses people actually say. openWakeWord
# trains one model over the whole list, which is exactly what we want: any of
# these should wake it.
TARGET_PHRASES = [
    "hey aitor",        # EN: "hey eye-tor"
    "hey aytor",        # EN respelling, pulls the generator toward "ay"
    "hey eitor",
    "ey aitor",         # ES: no aspirated h
    "oye aitor",        # ES natural equivalent of "hey"
    "hola aitor",
]

# Piper voices used to synthesize the positive samples. Mixing locales is what
# makes the model bilingual.
PIPER_VOICES = [
    "en_US-libritts_r-medium",
    "en_GB-alba-medium",
    "es_ES-davefx-medium",
    "es_MX-ald-medium",
]

CONFIG_NAME = "hey_aitor.yaml"


def config_yaml(out_dir: Path) -> str:
    phrases = "\n".join(f"  - {p}" for p in TARGET_PHRASES)
    voices = "\n".join(f"  - {v}" for v in PIPER_VOICES)
    return f"""# openWakeWord training config — bilingual "Hey Aitor"
# Generated by voice/train_wakeword.py
#
# Feed this to openWakeWord's automatic_model_training notebook, or to
# `python -m openwakeword.train --training_config {CONFIG_NAME}`.

model_name: hey_aitor

target_phrase:
{phrases}

# Bilingual on purpose: EN and ES voices in the same positive set so one model
# fires on both pronunciations of "Aitor".
tts_voices:
{voices}

# Sample counts. The defaults in the notebook are lower; a name this short needs
# more examples to avoid false accepts on "hey" alone.
n_samples: 30000
n_samples_val: 2000

# Hard negatives that matter for this phrase specifically.
custom_negative_phrases:
  - hey
  - hey there
  - hey siri
  - eight or
  - a tour
  - doctor
  - actor
  - editor
  - auditor
  - hey google
  - oye
  - ahora
  - autor
  - error

augmentation_batch_size: 16
target_accuracy: 0.7
target_recall: 0.5
target_false_positives_per_hour: 0.2

output_dir: {out_dir.as_posix()}
"""


COLAB_RECIPE = """
No local training extras found — use the free Colab notebook instead.

  1. Open:
     https://colab.research.google.com/github/dscripka/openWakeWord/blob/main/notebooks/automatic_model_training.ipynb
  2. Runtime -> Change runtime type -> Hardware accelerator -> GPU -> Save.
  3. Upload the config this script just wrote ({config_path}) and point the
     notebook's `training_config` at it, OR paste the target_phrase and
     tts_voices lists from it into the notebook's config cell.
     The bilingual voice list is the part that matters -- do not drop the
     es_ES / es_MX voices, they are what make it hear a Spanish "Aitor".
  4. Runtime -> Run all. Expect 30-60 minutes on a GPU.
  5. Download `hey_aitor.onnx` from the Colab file browser (left sidebar).
  6. Put it here:
     {model_path}
  7. Restart voice. You should see: Wake word active -- say 'Hey Aitor'

Tuning afterwards:
  too many false triggers -> CLAUDBOT_VOICE_WAKE_THRESHOLD=0.6
  does not hear you       -> CLAUDBOT_VOICE_WAKE_THRESHOLD=0.4, and check the
                             mic with `python -m voice.devices`
  wakes on other people   -> train the speaker verifier:
                             python -m voice.record_samples
"""


def write_config() -> Path:
    out_dir = Path(cfg.MODELS_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / CONFIG_NAME
    path.write_text(config_yaml(out_dir), encoding="utf-8")
    print(f"\nWrote training config: {path}")
    return path


def try_local_training(config_path: Path) -> bool:
    """Run openWakeWord's trainer if the training extras are installed."""
    try:
        import openwakeword.train  # noqa: F401
    except Exception:
        return False

    print("\nopenWakeWord training extras found — training locally.")
    print("This takes 30-60 minutes on a GPU and much longer on CPU.\n")
    import subprocess

    cmd = [sys.executable, "-m", "openwakeword.train",
           "--training_config", str(config_path)]
    try:
        return subprocess.run(cmd).returncode == 0
    except Exception as e:
        print(f"Local training failed: {e}")
        return False


def main(argv: list[str]) -> int:
    config_path = write_config()
    model_path = Path(cfg.WAKE_MODEL)

    if "--config" in argv:
        print(COLAB_RECIPE.format(config_path=config_path, model_path=model_path))
        return 0

    if try_local_training(config_path):
        print(f"\nDone. Make sure the model ends up at: {model_path}")
        return 0

    print(COLAB_RECIPE.format(config_path=config_path, model_path=model_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
